# Practica 4 
### Amparo Rubio Bellón y Jorge Zurdo Izquierdo

>Aplicacion de prediccion de una red neuronal entrenada.
>La practica aplica el algoritmo de feedforward a una serie de ejemplos partiendo de pesos de una red entrenada.



In [1]:
from scipy.io import loadmat
import utils as util
import ANN
import numpy as np

# Se cargan los datos de las imágenes y se "aplanan"
# Las imagenes pasan de ser 20x20 a un array de 400 
data = loadmat('data/ex3data1.mat', squeeze_me=True)
y = data['y']
X = data['X']

# Se cargan los pesos de la red entrenada
weights = loadmat('data/ex3weights.mat')
theta1, theta2 = weights['Theta1'], weights['Theta2']

# Hace las predicciones de TODO x
predictions = ANN.predict(theta1, theta2, X)

# Calcula la precision como un porcentaje
accuracy = np.mean(predictions == y) * 100
print(f'Porcentaje de aciertos de la red: {accuracy}%')


Porcentaje de aciertos de la red: 97.52%


In [10]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

# Matriz que muestra los aciertos y errores de la red para los valores posibles
# indica en la primera fila, que los valores reales de 1 son 496 y que algunos se han leido como 4, 6, 8 y 9
cm = confusion_matrix(y, predictions)
print(cm)

# Cantidad de aciertos respecto a los falsos positivos
# TP/TP+FP
precision = precision_score(y == 0, predictions == 0)
print(f'Porcentaje de positivos que no fueron falsos: {precision}')

# TP/TP+FN
recall = recall_score(y == 0, predictions == 0)
print(f'Porcentaje de positivos verdaderos: {recall}')

# 2*(Precision*Recall)/(Precision+Recall)
# Media armónica entre precision y recall
# Sirve para comprobar si hay mucho falso positivo o falso negativo
f1 = f1_score(y == 0, predictions == 0)
print(f'F1 Score: {f1}')

[[496   0   0   0   1   0   1   0   1   1]
 [  0 491   1   1   2   0   0   1   3   1]
 [  3   1 485   0   3   1   3   1   2   1]
 [  0   2   2 480   0   8   1   4   1   2]
 [  0   2   2   0 484   0   3   0   1   8]
 [  0   0   1   4   1 492   2   0   0   0]
 [  2   2   0   0   0   3 493   0   0   0]
 [  1   3   2   1   4   0   0 485   0   4]
 [  0   4   1   1   2   1   0   0 491   0]
 [  3   2   0   4   2   1   1   5   3 479]]
Porcentaje de positivos que no fueron falsos: 0.9821782178217822
Porcentaje de positivos verdaderos: 0.992
F1 Score: 0.9870646766169154
