# Practica 5
## Jorge Zurdo Izquierdo

1. Desarrollo del algoritmo Feedforward
Algoritmo que implementa el `crecimiento` de la capa inicial de neuronas (imagen 20x20 aplanada a 400).
Se crea 1 o más capas ocultas con valores "aleatorios"denominados `pesos` conocidos como `Theta` que conectan las capas.
La primera capa realiza una operacion dot matrix que multiplica EN la matrix inicial (400) cada valor por un peso diferente (400) y se lo suma a las neuronas intermedias (25). Esto significa que, cada una de las 25 neuronas intermedias es el resultado de 400 neuronas multiplicadas por su peso especifico para si misma (400 * 25).
`Neurona Intermedia 1 = Neurona 1 * Peso intermedia 1 + neurona 2 * Peso intermedia 1....
`Neurona Intermedia 2 = Neurona 1 * Peso intermedia 2 + neurona 2 * Peso intermedia 2.... 

2. Desarollo de función de coste
Se llama `coste` pero lo que mide es el `error`. Se coge la `capa salida`, se compara con el resultado esperado para la imagen inicial, y si es incorrecta, se usa la función MSE para calcular cuanto nos hemos desviado.
Se calcula sobre cada capa `Theta`

3. Desarrollo del algoritmo Backdropagation
Algoritmo que implementa el `aprendizaje`

- One-Hot Encoding se usa para codificar las salidas, eso quiere decir que el vector de 10 valores con un 1 en uno de ellos y 0 en el resto indica cual de los valores de 0-9 leemos, (0010000000 = 2)
- Alpha
- Lambda


In [1]:
from scipy.io import loadmat, savemat
from sklearn.preprocessing import OneHotEncoder

# Imágenes de entrenamiento cargadas en una matriz plana
data = loadmat('data/ex3data1.mat', squeeze_me=True)

# Pesos de la red neuronal YA ENTRENADOS
weights = loadmat('data/ex3weights.mat')
theta1, theta2 = weights['Theta1'], weights['Theta2']

y = data['y']
X = data['X']   # Dataset de entrenamiento (5000 imagenes 20x20 [5000x400])

#print(y.shape)
y = y.reshape(-1,1) 
encoder = OneHotEncoder(sparse_output = False) # La matriz sparse daba error en la funcion de coste
Y = encoder.fit_transform(y)
#print(y.shape)  # Matriz de salida original (5000 valores de 0-9 [5000x1])
#print(y)
#print(X.shape)
#print(X)
#print(Y.shape)
#print(Y)    # Matriz de salida codificada en OneHot (5000 valores de 1000000000-0000000001 [5000x10])


# Implementacion

In [2]:
from utils import checkNNGradients
import ann as net

c = net.cost(theta1,theta2,X,Y,1)   # El ultimo parametro es el lambda
print(f"Cost = {c}")


checkNNGradients(net.backProp)

# entrenamiento

theta1, theta2 = net.training(X,Y,25,10,0.12,1,1,1000)  # El ultimo parametro es el lambda



Cost = 0.384487796242894
If your backpropagation implementation is correct, then 
the relative difference will be small (less than 1e-9). 
Relative Difference: 0.111026
Epoch 0, Cost: 7.085720082338404
Epoch 100, Cost: 3.1650853915761883
Epoch 200, Cost: 2.8768530678141855
Epoch 300, Cost: 2.325403446469916
Epoch 400, Cost: 1.901275768590724
Epoch 500, Cost: 1.6215887526734079
Epoch 600, Cost: 1.4275073799306464
Epoch 700, Cost: 1.2848240851566375
Epoch 800, Cost: 1.1753744100058872
Epoch 900, Cost: 1.089209671511629


In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix

Y_output = net.predict(theta1,theta2,X)
print(Y_output)

print(np.sum(Y_output == y) / y.shape[0] * 100)  # Porcentaje de aciertos

cm = confusion_matrix(y, Y_output)
print(cm)

(5000, 400)
(5000, 10)
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [0]]
89.75999999999999
[[486   0   0   3   0   3   5   2   1   0]
 [  0 488   1   1   1   3   1   1   4   0]
 [ 10  12 432   7  11   0   6   8  14   0]
 [  2   4  13 443   1  19   2   6   6   4]
 [  1   4   5   0 464   1   6   0   1  18]
 [ 13   3   5  34  14 391  13   1  21   5]
 [  5   4   6   0   4   3 474   0   4   0]
 [  4  12   6   1   6   2   0 457   1  11]
 [  5   8  13  10   4  12   8   0 433   7]
 [ 11   2   2   6  25   5   1  23   5 420]]
