# Practica 5
## Amparo Rubio Bellon y Jorge Zurdo Izquierdo

### 1. Desarrollo del algoritmo Feedforward

Algoritmo que implementa el `crecimiento` de la capa inicial de neuronas (imagen 20x20 aplanada a 400).
Se crea 1 o más capas ocultas con valores "aleatorios"denominados `pesos` conocidos como `Theta` que conectan las capas.

La primera capa realiza una operacion dot matrix que multiplica EN la matrix inicial (400) cada valor por un peso diferente (400) y se lo suma a las neuronas intermedias (25). Esto significa que, cada una de las 25 neuronas intermedias es el resultado de 400 neuronas multiplicadas por su peso especifico para si misma (400 * 25).

`Neurona Intermedia 1 = Neurona 1 * Peso intermedia 1 + neurona 2 * Peso intermedia 1....`

`Neurona Intermedia 2 = Neurona 1 * Peso intermedia 2 + neurona 2 * Peso intermedia 2....`

### 2. Desarollo de función de coste.

Se llama `coste` pero lo que mide es el `error`. Se coge la `capa salida`, se compara con el resultado esperado para la imagen inicial, y si es incorrecta, se usa la función MSE para calcular cuanto nos hemos desviado.
Se calcula sobre cada capa `Theta`

### 3. Desarrollo del algoritmo Backpropagation

Algoritmo que implementa el `aprendizaje`

- One-Hot Encoding se usa para codificar las salidas, eso quiere decir que el vector de 10 valores con un 1 en uno de ellos y 0 en el resto indica cual de los valores de 0-9 leemos, (0010000000 = 2)
- Alpha
- Lambda


In [1]:
from scipy.io import loadmat, savemat
from sklearn.preprocessing import OneHotEncoder
import ann as red

# Imágenes de entrenamiento cargadas en una matriz plana
data = loadmat('data/ex3data1.mat', squeeze_me=True)

# Pesos de la red neuronal YA ENTRENADOS
weights = loadmat('data/ex3weights.mat')
theta1, theta2 = weights['Theta1'], weights['Theta2']

y = data['y']
X = data['X']   # Dataset de entrenamiento (5000 imagenes 20x20 [5000x400])

#print(y.shape)
y = y.reshape(-1,1) 
encoder = OneHotEncoder(sparse_output = False) # La matriz sparse daba error en la funcion de coste
Y = encoder.fit_transform(y)
#print(y.shape)  # Matriz de salida original (5000 valores de 0-9 [5000x1])
#print(y)
#print(X.shape)
#print(X)
#print(Y.shape)
#print(Y)    # Matriz de salida codificada en OneHot (5000 valores de 1000000000-0000000001 [5000x10])

#red.feedForward(theta1, theta2, X)


# Implementacion

In [2]:
from utils import checkNNGradients
import ann as net

c = net.cost(theta1,theta2,X,Y,1)   # El ultimo parametro es el lambda
#print(f"Coste en la red anterior = {c}") # Devuelve 0.2876291651613189 antes de MSE
print(f"Coste en la red anterior = {c}") # Devuelve 0.384487796242894 DESPUES de MSE


checkNNGradients(net.backProp)

# entrenamiento

theta1, theta2 = net.training(X,Y,25,10,0.12,1,1,1000)  # El ultimo parametro es el lambda



Coste en la red anterior = 0.384487796242894
If your backpropagation implementation is correct, then 
the relative difference will be small (less than 1e-9). 
Relative Difference: 2.55759e-11
Epoch 0, Cost: 6.89898722001831
Epoch 100, Cost: 1.2625588399345045
Epoch 200, Cost: 0.8251643418719662
Epoch 300, Cost: 0.6719899660939913
Epoch 400, Cost: 0.5978228931437948
Epoch 500, Cost: 0.5524044653296246
Epoch 600, Cost: 0.5205196825918178
Epoch 700, Cost: 0.4963289185185623
Epoch 800, Cost: 0.47712209942039824
Epoch 900, Cost: 0.4614015275290658


In [7]:
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

Y_output = net.predict(theta1,theta2,X)

accuracy = np.sum(Y_output == y) / y.shape[0] * 100  # Porcentaje de aciertos
print(f"Porcentaje de aciertos de la red: {accuracy}%")

cm = confusion_matrix(y, Y_output)
print(cm)

precision = precision_score(y == 0, Y_output == 0)
print(f'Porcentaje de positivos que no fueron falsos: {precision}')

recall = recall_score(y == 0, Y_output == 0)
print(f'Porcentaje de positivos verdaderos: {recall}')

f1 = f1_score(y == 0, Y_output == 0)
print(f'F1 Score: {f1}')

(5000, 400)
(5000, 10)
porcentaje de aciertos de la red: 95.84%
[[495   0   0   1   1   0   1   1   1   0]
 [  0 489   2   2   2   2   0   2   1   0]
 [  1   3 465   3   4   3   3   5  11   2]
 [  0   3   9 465   0  12   1   5   3   2]
 [  0   2   1   0 486   0   3   0   1   7]
 [  3   1   4  10   4 473   2   0   2   1]
 [  2   2   0   0   0   5 490   0   1   0]
 [  1   7   3   0   6   1   0 474   1   7]
 [  0   3   1   6   2   2   0   1 483   2]
 [  3   2   1   4   4   2   1   9   2 472]]
Porcentaje de positivos que no fueron falsos: 0.9801980198019802
Porcentaje de positivos verdaderos: 0.99
F1 Score: 0.9850746268656716
